blacklistedItems = blacklistedItems or {}

blacklistedItems = {
    `prop_streetlight_01`,
    `prop_rub_cage01b`,
    `prop_bin_01a`,
    `prop_news_disp_02a`,
    `prop_forsale_dyn_01`,
    `prop_forsale_dyn_02`,
    `prop_forsale_lenny_01`,
    `prop_forsale_lrg_01`,
    `prop_forsale_lrg_02`,
    `prop_bench_01a`,
    `prop_bench_01b`,
    `prop_bench_01c`,
    `prop_bench_02`,
    `prop_bench_03`,
    `prop_bench_04`,
    `prop_bench_05`,
    `prop_bench_06`,
    `prop_bench_07`,
    `prop_bench_08`,
    `prop_bench_09`,
    `prop_bench_10`,
    `prop_bench_11`,
    `hei_heist_stn_benchshort`,
}